services:
  - type: web
    name: jordan-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # set in Render dashboard
